[build]
publish = "public/"
command = "hugo --gc --minify"

[build.environment]
TZ = "America/Los_Angeles"

[context.production.environment]
HUGO_VERSION = "0.110.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --baseURL $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.110.0"
