display_url: https://blog.millerti.me

backend:
  name: git-gateway
  squash_merges: true

# Enables Netlify CMS's editorial workflow:
# https://www.netlifycms.org/docs/configuration-options/#publish-mode
publish_mode: editorial_workflow

media_folder: "static/images"
public_folder: "/images"

collections:
    # Used in routes, e.g., /admin/collections/blog
  - name: "posts"
    # What to call items in the CMS
    label: "Posts"
    label_singular: "Post"
    # Where to store posts (relative to the project root)
    folder: "content/posts"
    # The filename slug to use when saving posts
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    # Support Hugo page bundles that puts index.md and images in folders named by slug
    path: "{{slug}}/index"
    media_folder: "images"
    public_folder: "images"
    # Allow for posts to be created in the CMS
    create: true
    # Save posts with .md extension
    extension: "md"
    # Use TOML frontmatter (delimiter: +++)
    format: "toml-frontmatter"
    # Post frontmatter
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Post Categories (comma-separated)", name: "categories", widget: "list", default: []}
      - {label: "Meta Keywords (comma-separated)", name: "keywords", widget: "list", default: []}
      - {label: "Has Code? (enables highlighting)", name: "hasCode", widget: "boolean", default: false}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}
    summary: "{{year}}-{{month}}-{{day}} - {{title}}"
    preview_path: "{{year}}/{{month}}/{{day}}/{{title}}/"
    view_filters:
      - label: Drafts
        field: "draft"
        pattern: true
    view_groups:
      - label: Year
        field: date
        # groups items based on the value matched by the pattern
        pattern: \d{4}
      - label: Drafts
        field: draft
  - name: "gaming"
    label: "Gaming"
    label_singular: "Gaming"
    folder: "content/gaming"
    # The filename slug to use when saving posts
    slug: "{{slug}}"
    # Support Hugo page bundles that puts index.md and images in folders named by slug
    path: "{{year}}/{{slug}}/index"
    media_folder: "images"
    public_folder: "images"
    # Allow for posts to be created in the CMS
    create: true
    # Save posts with .md extension
    extension: "md"
    # Use TOML frontmatter (delimiter: +++)
    format: "toml-frontmatter"
    # Post frontmatter
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Gaming Year", name: "gaming", widget: "date", format: "YYYY"}
      - {label: "Console Name", name: "system", widget: "string", default: "PS5|PC|Switch"}
      - {label: "Story Completed?", name: "completed", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}
    summary: "{{year}} - {{title}}"
    preview_path: "gaming/{{year}}/{{title}}/"
